---
title: |
    | Coursera Finance Specialisation (U Michigan)
    | M2 -- Risk and Return
    | Week 3 -- What is Risk?
author: "Joe Nguyen"
date: "03 December 2015"
output: html_document
---

```{r, echo=FALSE}
rm(list = ls())

# Change working directory
dirBase <- "/home/joe/Documents/01-coursera/02-finance"
dirWorking <- "/02-risk-and-return/r-code"
setwd(paste0(dirBase, dirWorking))

# Generic finance functions
source(paste0(dirBase, "/01-tvm/r-code/func_finance.R"))
```


## 3.3 What is Risk?

### Fundamental Sources of Risk

**1. Economy-wide / Macro / Systematic**

Examples:

- big oil shock
- interest rate changes
- government or public policies

**2. Specific / Idiosyncratic / Unique**

- technological change specific to your product
- management's investment decisions



## 3.8 Recap Module 3

### Diversification

Portfolio diversification removes specific/unique risks of individual securities. Thus, the average risk (standard deviation) of a portfolio is **always lower** than the collective risk of individual securities/stocks in the market. Diversification states that:
$$
\begin{align}
\sigma_p   &< \frac{1}{n} \sum \sigma_i \\
\sigma_p^2 &< \frac{1}{n^2} \left\{ \sum \sigma_i \right\}^2
\end{align}
$$
where $\sigma_p$ is the portfolio risk (standard deviation), $\sigma_i$ is risk of individual security. For two securities,
$$
\begin{align}
\sigma^2(R_p) = \sigma_p^2 &= x_a^2 \sigma_a^2 + x_b^2 \sigma_b^2 + 2 x_a x_b \sigma_{ab} \\
                           &= x_a^2 \sigma_a^2 + x_b^2 \sigma_b^2 + 2 x_a x_b \rho_{ab} \sigma_a \sigma_b
\end{align}
$$
We can see
$$
\sigma_p^2 = \frac{1}{n^2} \left\{ \sum_{i=1}^2 \sigma_i \right\}^2
$$
only if $\rho_{ab} = 1$; that is, securities are perfectly correlated, in which case diversification has no benefit. Perfectly correlated securities is highly unlikely.


### Valuing a New Company

To value a new company, examine:

- its cashflow
- the cost of capital (assets) (market interest rate) of a comparable firm: $r_a$

Cashflow is known; a signature of the company. However, we don't know the cost of capital, which is what we want to determine. Now, **real assets** don't trade, but **equity** and **debt** (collectively known as liabilities) are publically traded.

To simplify the problem, assume debt is zero (firm has no debt). Then, the risk and return of the equity is **identical** to the risk and return of real assets. The reason is that the balance sheet balances: the value of assets is completely financed by the equity.


